### ISSUE TITLE
Unable to assign Private IP with assign_private_ip.py script with EMR version 5.30.0

### ISSUE THREAD

**Issue by ArjunAhuja-git** [awslabs/aws-support-tools#129]
I am unable to assign Private IP address with assign_private_ip.py script with EMR version 5.30.0, I am running this script as bootstrap action. 
This is the error I am getting: 
```
iptables v1.8.2 (legacy): option "--to-destination" requires an argument
Try `iptables -h' or 'iptables --help' for more information.
Traceback (most recent call last):
  File "/emr/instance-controller/lib/bootstrap-actions/4/assign_private_ip.py", line 38, in <module>
    subprocess.check_call(['sudo iptables -t nat -A PREROUTING -d %s -j DNAT --to-destination %s' % (private_ip, primary_ip)], shell=True)
  File "/usr/lib64/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo iptables -t nat -A PREROUTING -d 172.31.110.200 -j DNAT --to-destination ']' returned non-zero exit status 2
```

On debugging further I found that this command in code is returning an empty string:
```
#Configure iptablles rules such that traffic is redirected from the secondary to the primary IP address:
    primary_ip = subprocess.check_output(['/sbin/ifconfig eth0 | grep \'inet addr:\' | cut -d: -f2 | awk \'{ print $1}\''], shell=True).strip()
```

Please help me resolve this.

**Comment by henriquesantanati** [comment]
The assign_private_ip script has been updated for Python 3 compatibility (PR #241). If you're still experiencing issues on a current EMR version, please reopen or file a new issue.
