### ISSUE TITLE
MWAA script fails to run due to a missed exceptions

### ISSUE THREAD

**Issue by dburiak** [awslabs/aws-support-tools#185]
Console output: 

```
python3 verify_env.py --envname some-airflow-name --profile prod
please send support the following information
If a case is not opened you may open one here https://console.aws.amazon.com/support/home#/case/create
Please make sure to NOT include any personally identifiable information in the case

AirflowConfigurationOptions :  {'webserver.default_ui_timezone': 'America/New_York'}
AirflowVersion :  1.10.12
Arn :  arn:aws:airflow:us-east-1:*************:environment/some-airflow-name
CreatedAt :  2021-12-15 16:03:46+02:00
DagS3Path :  dags
EnvironmentClass :  mw1.small
ExecutionRoleArn :  arn:aws:iam::437795906767:role/some-airflow-name-execution-role
KmsKey :  arn:aws:kms:us-east-1:437795906767:key/***************************************
LastUpdate :  {'CreatedAt': datetime.datetime(2021, 12, 15, 16, 3, 46, tzinfo=tzlocal()), 'Error': {'ErrorCode': 'INCORRECT_CONFIGURATION', 'ErrorMessage': 'You may need to check the execution role permissions policy for your environment, and that each of the VPC networking components required by the environment are configured to allow traffic. Troubleshooting: https://docs.aws.amazon.com/mwaa/latest/userguide/troubleshooting.html'}, 'Status': 'FAILED'}
LoggingConfiguration :  {'DagProcessingLogs': {'Enabled': True, 'LogLevel': 'INFO'}, 'SchedulerLogs': {'Enabled': True, 'LogLevel': 'INFO'}, 'TaskLogs': {'Enabled': True, 'LogLevel': 'INFO'}, 'WebserverLogs': {'Enabled': True, 'LogLevel': 'INFO'}, 'WorkerLogs': {'Enabled': True, 'LogLevel': 'INFO'}}
MaxWorkers :  10
MinWorkers :  1
Name : some-airflow-name
NetworkConfiguration :  {'SecurityGroupIds': ['sg-******************'], 'SubnetIds': ['subnet-******************', 'subnet-*********************']}
PluginsS3ObjectVersion :  D47kYIoU_IaRmwh8hM_w_ii1SzZCefUr
PluginsS3Path :  plugins.zip
RequirementsS3ObjectVersion :  QK0GjP.xqPS_NYQzzP.pkwDDTPAWNxTC
RequirementsS3Path :  requirements.txt
Schedulers :  1
ServiceRoleArn :  arn:aws:iam::*******************:role/aws-service-role/airflow.amazonaws.com/AWSServiceRoleForAmazonMWAA
SourceBucketArn :  arn:aws:s3:::some-airflow-name
Status :  CREATE_FAILED
Tags :  {'application_family': 'test', 'environment': 'qa', 'terraformed': 'true', 'service_name': 'test-managed-airflow'}
WebserverAccessMode :  PRIVATE_ONLY
WeeklyMaintenanceWindowStart :  TUE:07:00
VPC:  vpc-**********************

### Checking the IAM execution role arn:aws:iam::******************:role/some-airflow-name-airflow-execution-role using iam policy simulation
Found Customer managed CMK
Traceback (most recent call last):
  File "verify_env.py", line 963, in <module>
    check_iam_permissions(env, iam)
  File "verify_env.py", line 252, in check_iam_permissions
    "arn:aws:sqs:" + REGION + ":*:airflow-celery-*"
TypeError: can only concatenate str (not "NoneType") to str

```

**Comment by henriquesantanati** [comment]
Fixed by PR #246 (item 12: region is now a required argument, eliminating the NoneType concatenation). Closing
