### ISSUE TITLE
MWAA: testing connectivity fails with "KeyError - 'PortRange'"

### ISSUE THREAD

**Issue by ivica-k** [awslabs/aws-support-tools#191]
Hey :)

Thank you for providing the `verify_env.py` script for MWAA. However, running it fails with an error in the `### Testing connectivity to the following service endpoints from MWAA enis...` step. The error is not apparent from the script itself but is clearly visible from SSM Automation execution. This is the traceback

```
Traceback (most recent call last):
  File "/tmp/ea8016b8-bc1f-4d1c-9910-cd137a8b0a0d-2022-01-31-15-23-46/customer_script.py", line 80, in eval_nat_nacls
    check_ingress_from_dst(ingress_acls, dst_ip)
  File "/tmp/ea8016b8-bc1f-4d1c-9910-cd137a8b0a0d-2022-01-31-15-23-46/customer_script.py", line 41, in check_ingress_from_dst
    if ((acl.get('Protocol') == '-1') or (set(range(src_port_from,src_port_to)).issubset(range(acl['PortRange']['From'], acl['PortRange']['To'] +1)))):
KeyError: 'PortRange'
```

I'd be happy to provide more information.

**Comment by twknight** [comment]
Unfortunately, this is still an issue.

(Not very helpful, but consider this my upvote!)

**Comment by henriquesantanati** [comment]
The SSM ConnectivityTroubleshooter automation invocation that produced this KeyError was removed in PR #246 (merged Nov 2025). The tool no longer calls SSM automation for connectivity testing. Closing.
