### ISSUE TITLE
MWAA verify TOP_LEVEL_DOMAIN is None

### ISSUE THREAD

**Issue by nagulvali555** [awslabs/aws-support-tools#220]
MWAA verify script fails with below error

```
top_level_domain = TOP_LEVEL_DOMAIN.split(".").reverse().join(".")

AttributeError: 'NoneType' object has no attribute 'join'
```
the above join statement seems to be wrong

**Comment by devstek** [comment]
Same here:

```
### Trying to verify if route tables are valid...
Route Table: rtb-123456789 does not have a route to a NAT Gateway
checking for VPC endpoints to airflow, s3, sqs, kms, ecr, and monitoring
Traceback (most recent call last):
  File "/home/t1-712980/git/aws-support-tools/MWAA/verify_env/verify_env.py", line 989, in <module>
    check_routes(env, subnets, subnet_ids, ec2)
  File "/home/t1-712980/git/aws-support-tools/MWAA/verify_env/verify_env.py", line 742, in check_routes
    check_service_vpc_endpoints(ec2_client, input_subnets)
  File "/home/t1-712980/git/aws-support-tools/MWAA/verify_env/verify_env.py", line 658, in check_service_vpc_endpoints
    top_level_domain = TOP_LEVEL_DOMAIN.split(".").reverse().join(".")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'join'
```

**Comment by yingchenjun** [comment]
Got the same error here.  do we know the cause here?

```
### Trying to verify if route tables are valid...
Route Table: rtb-xxxxxxxxxx does not have a route to a NAT Gateway
checking for VPC endpoints to airflow, s3, sqs, kms, ecr, and monitoring
Traceback (most recent call last):
  File "aws-support-tools/MWAA/verify_env/verify_env.py", line 989, in <module>
    check_routes(env, subnets, subnet_ids, ec2)
  File "aws-support-tools/MWAA/verify_env/verify_env.py", line 742, in check_routes
    check_service_vpc_endpoints(ec2_client, input_subnets)
  File "aws-support-tools/MWAA/verify_env/verify_env.py", line 658, in check_service_vpc_endpoints
    top_level_domain = TOP_LEVEL_DOMAIN.split(".").reverse().join(".")
AttributeError: 'NoneType' object has no attribute 'join'
```

**Comment by henriquesantanati** [comment]
This was fixed by PR #222 (merged Aug 2023). Closing.
