### ISSUE TITLE
Uncaught Exception Cannot find module aws-sdk

### ISSUE THREAD

**Issue by uyuyangezgin** [awslabs/aws-support-tools#229]
Hi All,

I try to create AWS ses-bounce-complaint-reports via CloudFormation. It gets some errors related to nodejs (nodejs16.x,nodejs18.x, and nodejs20.x) and python runtime (python3.9).

https://github.com/awslabs/aws-support-tools/blob/master/SES/SESReports/ses-reports.yaml

`{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'aws-sdk'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'aws-sdk'",
        "Require stack:",
        "- /var/task/index.js",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1087:17)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)",
        "    at async start (file:///var/runtime/index.mjs:1282:23)",
        "    at async file:///var/runtime/index.mjs:1288:1"
    ]
}`

`[ERROR] Runtime.UserCodeSyntaxError: Syntax error in module 'index': invalid syntax (index.py, line 22)
Traceback (most recent call last):
  File "/var/task/index.py" Line 22
            print 'Exception occured :' + str(e)`

Could you help me with this case? 
Thanks a lot.

**Comment by henriquesantanati** [comment]
The SES Reports tool has not been maintained since 2019 and targets Lambda runtimes that are now end-of-life. The fix requires migrating from aws-sdk v2 to v3 (Node.js) and from Python 2 print statements to Python 3. Given that Amazon Pinpoint now provides native email dashboards covering the same use case, this tool is being archived. Closing as wontfix.
