### ISSUE TITLE
SES Reports - Error with lambda -  TypeError: Cannot read property 'source' of undefined

### ISSUE THREAD

**Issue by YoShiiro** [awslabs/aws-support-tools#64]
Hello i've followed the dashboard creation amazon ses reports [Here on aws](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/bouncecomplaintdashboard.html) and i got an error when lambda try to read the SQS queue not empty. When the queue is empty don't have any errors.

Keys & Value config are the same as in : https://docs.aws.amazon.com/ses/latest/DeveloperGuide/dashboardcreatelambdafunction.html
QueueURl = good one no error in logs
Region = good one 
ToAddr = verified email
SrcAddr = verified email too
Bucketname = existing one
BucketPrefix = folders existing in S3 bucket

If someone got an idea ? i just took the sesreports.zip and import it in lambda and using the keys/values as asked.

START RequestId: f8b3ab50-f167-11e8-8265-6bd008a84f1b Version: $LATEST
2018-11-26T10:42:29.152Z	f8b3ab50-f167-11e8-8265-6bd008a84f1b	Reading from: https://sqs.somewhereonaws.amazonaws.com/......../nameofmyqueue
2018-11-26T10:42:29.212Z	f8b3ab50-f167-11e8-8265-6bd008a84f1b	Reading queue, size = 7
2018-11-26T10:42:29.284Z	f8b3ab50-f167-11e8-8265-6bd008a84f1b	TypeError: Cannot read property 'source' of undefined
    at Response.sqs.receiveMessage (/var/task/index.js:128:43)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
END RequestId: f8b3ab50-f167-11e8-8265-6bd008a84f1b
REPORT RequestId: f8b3ab50-f167-11e8-8265-6bd008a84f1b	Duration: 183.58 ms	Billed Duration: 200 ms 	Memory Size: 512 MB	Max Memory Used: 35 MB	
RequestId: f8b3ab50-f167-11e8-8265-6bd008a84f1b Process exited before completing request

**Comment by YoShiiro** [comment]
If i put some trace in script to check what happen it looks like when they going to parse json in sqs.receiveMessage there is no information in it

**add this line at pos 123 :**
_console.log("data with message = " + data.Messages);
                if (data.Messages) {
                    var message = data.Messages[0];
                    body = JSON.parse(message.Body);
                    console.log("body OK =" + body);
                    msg = JSON.parse(body.Message);
                    console.log("msg OK =" + msg);
                    var source = msg.mail.source;
                    console.log("variable source ok");_

**And got this in logs :**
2018-11-26T14:26:51.521Z	50cea954-f187-11e8-8654-25a87eea46e6	data with message = [object Object]
2018-11-26T14:26:51.521Z	50cea954-f187-11e8-8654-25a87eea46e6	body OK =[object Object]
2018-11-26T14:26:51.521Z	50cea954-f187-11e8-8654-25a87eea46e6	msg OK =[object Object]
2018-11-26T14:26:51.522Z	50cea954-f187-11e8-8654-25a87eea46e6	TypeError: Cannot read property 'source' of undefined

**Comment by rsavordelli** [comment]
Probably you have a strange message in your SQS. That error means the parser failed to find the key/value pair in the message retrieved from the queue. Probably a subscription message. The queue usually is emptied after the default retention period - which I believe it's 4 days. So the issue should be fixed by itself. Try to purge the queue (delete all messages in queue) and start again in case you still have messages in the queue which are not SES notifications.

**Comment by lpierillas** [comment]
Closing this for now as this has been stale for while, please reopen if needed.
